# Generated by Django 3.0.5 on 2020-05-26 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditrequest',
            name='modified_time',
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время отправки'),
            preserve_default=False,
        ),
    ]
