# Generated by Django 3.0.5 on 2020-05-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200526_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcreditform',
            name='passport_num',
            field=models.CharField(max_length=40, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='clientcreditform',
            name='phone_num',
            field=models.CharField(max_length=40, verbose_name='Номер телефона'),
        ),
    ]
